tasks:
  - name: Setup & Build
    before: sdk install java 19-tem < /dev/null
    init: mvn install -DskipTests=true
vscode:
  extensions:
    - "vscjava.vscode-java-pack"
    - "redhat.fabric8-analytics"
